# Generated by Django 5.2.1 on 2025-10-23 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('varta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='quickresponse',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('speech', 'Speech'), ('quick_response', 'Quick Response')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='source_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='target_language',
            field=models.CharField(default='hi', max_length=10),
        ),
        migrations.AddField(
            model_name='conversation',
            name='translated_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quickresponse',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='quickresponse',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quickresponse',
            name='phrase',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
